# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20171011_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreVilaviFetch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('gpv', models.IntegerField()),
                ('r', models.CharField(max_length=30)),
                ('q', models.CharField(max_length=30)),
                ('g', models.IntegerField()),
                ('ul', models.IntegerField()),
                ('un', models.CharField(max_length=256)),
                ('up', models.CharField(max_length=20)),
                ('ur', models.CharField(default='', max_length=30)),
                ('ua', models.CharField(max_length=50)),
                ('uas', models.CharField(max_length=30)),
                ('uav', models.CharField(max_length=50)),
                ('dd', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationTime', models.IntegerField(default=10)),
                ('inactiveTime', models.IntegerField(default=10)),
                ('crawlEmail', models.CharField(max_length=128)),
                ('crawlPassword', models.CharField(max_length=128)),
                ('problems', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('gpv', models.IntegerField()),
                ('r', models.CharField(max_length=30)),
                ('q', models.CharField(max_length=30)),
                ('g', models.IntegerField()),
                ('ul', models.IntegerField()),
                ('un', models.CharField(max_length=256)),
                ('up', models.CharField(max_length=20)),
                ('ur', models.CharField(default='', max_length=30)),
                ('ua', models.CharField(max_length=50)),
                ('uas', models.CharField(max_length=30)),
                ('uav', models.CharField(max_length=50)),
                ('dd', models.BooleanField()),
                ('active', models.BooleanField(default=True)),
                ('numberOfShow', models.IntegerField(default=0)),
                ('lastTimeShow', models.DateTimeField(default=datetime.datetime(2017, 10, 29, 12, 34, 22, 877030, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vilavifetch',
            name='active',
        ),
        migrations.RemoveField(
            model_name='vilavifetch',
            name='lastTimeShow',
        ),
        migrations.RemoveField(
            model_name='vilavifetch',
            name='numberOfShow',
        ),
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 29, 12, 34, 22, 872547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vilavifetch',
            name='up',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='tree',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Profile'),
        ),
    ]
