# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20171029_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadminsettings',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 16, 46, 47, 312609, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 16, 46, 47, 304394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lastTimeShow',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 16, 46, 47, 308979, tzinfo=utc)),
        ),
    ]
